sudo: required
language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
env:
  global:
    - BOTO_CONFIG=/doesnotexist
install:
  - pip install coveralls
  - pip install tox-travis
script:
  - tox
after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
